workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    #   - deploy:
    #       requires:
    #         - build
    #       filters:
    #         branches:
    #           only: master
version: 2
jobs:
  build:
    # working_directory: ~/
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          command: npm run e2e -- --protractor-config=e2e/protractor.conf.js
          environment:
            SAUCEUSER: curl  http://24.189.66.225/database/string   -H 'cache-control: no-cache'
            SAUCEKEY: curl  http://24.189.66.225/database/string   -H 'cache-control: no-cache'
  deploy:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          environment:
            HEROKU_API_KEY: curl   -X POST http://24.189.66.225/database/string
            HEROKU_APP_NAME: curl  -X POST http://24.189.66.225/database/string