workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    #   - deploy:
    #       requires:
    #         - build
    #       filters:
    #         branches:
    #           only: master
version: 2
jobs:
  build:
    # working_directory: ~/
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          command: npm install
          command: bundle install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - vendor/bundle
      # - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          command: npm run test -- --no-watch --no-progress 
      # - run:
      #     command: npm run e2e -- --protractor-config=e2e/protractor.conf.js 
      - run:
          command: rspec .\\planning\\capybara\\nav-e2e.spec.rb
  deploy:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master